{% set version = '0.7.6' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ritis
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ritis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ritis/ritis_{{ version }}.tar.gz
  sha256: 4659dec79ca78e8cd848419387ef4c5d165d34e845f57bcc24ee3f551b2138a8

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-crul >=0.4.0
    - r-data.table >=1.9.6
    - r-jsonlite >=1.5
    - r-solrium >=1.0.2
    - r-tibble >=1.3.4
  run:
    - r-base
    - r-crul >=0.4.0
    - r-data.table >=1.9.6
    - r-jsonlite >=1.5
    - r-solrium >=1.0.2
    - r-tibble >=1.3.4

test:
  commands:
    - $R -e "library('ritis')"           # [not win]
    - "\"%R%\" -e \"library('ritis')\""  # [win]

about:
  home: https://github.com/ropensci/ritis
  license: MIT
  summary: An interface to the Integrated Taxonomic Information System ('ITIS') (<https://www.itis.gov>).
    Includes functions to work with the 'ITIS' REST API methods (<https://www.itis.gov/ws_description.html>),
    as well as the 'Solr' web service (<https://www.itis.gov/solr_documentation.html>).
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf

# Package: ritis
# Title: Integrated Taxonomic Information System Client
# Description: An interface to the Integrated Taxonomic Information System ('ITIS') (<https://www.itis.gov>). Includes functions to work with the 'ITIS' REST API methods (<https://www.itis.gov/ws_description.html>), as well as the 'Solr' web service (<https://www.itis.gov/solr_documentation.html>).
# Version: 0.7.6
# License: MIT + file LICENSE
# URL: https://github.com/ropensci/ritis
# BugReports: https://github.com/ropensci/ritis/issues
# Authors@R: person("Scott", "Chamberlain", role = c("aut", "cre"), email = "myrmecocystus@gmail.com", comment = c(ORCID = "0000-0003-1444-9135"))
# VignetteBuilder: knitr
# LazyData: true
# Encoding: UTF-8
# Language: en-US
# Imports: solrium (>= 1.0.2), crul (>= 0.4.0), jsonlite (>= 1.5), data.table (>= 1.9.6), tibble (>= 1.3.4)
# Suggests: roxygen2 (>= 6.1.1), knitr, testthat, webmockr, vcr
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2018-12-18 21:34:08 UTC; sckott
# Author: Scott Chamberlain [aut, cre] (<https://orcid.org/0000-0003-1444-9135>)
# Maintainer: Scott Chamberlain <myrmecocystus@gmail.com>
# Repository: CRAN
# Date/Publication: 2018-12-18 22:10:03 UTC
