{% set version = "0.7.2" %}

package:
  name: r-ritis
  version: {{ version }}

source:
  fn: ritis_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ritis_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ritis/ritis_{{ version }}.tar.gz
  sha256: a9b44be7850c9fd8351468ee3be9252e8dc68c4e7f1569ce48f303ccde868169

build:
  number: 0
  script: R CMD INSTALL --build .
  skip: True  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-crul >=0.4.0
    - r-data.table >=1.9.6
    - r-jsonlite >=1.5
    - r-solrium >=1.0.0
    - r-tibble >=1.3.4
  run:
    - r-base
    - r-crul >=0.4.0
    - r-data.table >=1.9.6
    - r-jsonlite >=1.5
    - r-solrium >=1.0.0
    - r-tibble >=1.3.4

test:
  commands:
    - $R -e "library('ritis')"  # [not win]
    - "\"%R%\" -e \"library('ritis')\""  # [win]

about:
  home: https://cran.r-project.org/web/packages/ritis
  license: MIT
  license_file: LICENSE
  summary: An interface to the Integrated Taxonomic Information System ('ITIS') (<https

extra:
  recipe-maintainers:
    - ocefpaf
