appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: hK/MHNrOFeuLUqDdDEXWuwoK+EGLjwuKjxro6sTc0C4PyMlftfDe/6Qjf3D62IaBOdiWcYT67AyvD22GvMRtinx4Y2EVN7O1n7dOnn/yjrxV9KRctqMliVD5DmVuF1acPmU++V2x3QjNchB46lUot2xLL/qHtijK/e9nO1myDsWQmbJ2cxq8YSw806sd5FjfjjXD9H7nny/n7u2rEy7LXlDEXjdH24f9Ag7OxRePVsyYxJtEmu9HYxU47WRJHLb6kezTOIba33r0f4YVwP/oJcm1NnCSNVBGJTLZxB9Dovo3tTpfZ8pdF5m/ehfaZQUT6f5VvRpQ9B22pp9WCtuD1zwVe126DuMFw1k3I+jZLbb+gq42OwVVgqWdkP+eIhedQOtkTy0pOanDu/eia+NcX7wfvIE+6/fQnwcMIFfpAeFRtGIc9Po78ZKw10gGFDNS5DbOC3itrIQ3nfxKfyl2Sm9mB5bFsqIBRGw0DDVPS6maIu/WZShdDZsH6HSjMENPWRE0DiPqTjgLHZU1NcttfeDpcfCoCHAI8e6pHWwnD3guLfwrHpSIaQAkEXzEFJ0Rt3/j/tjuqJxd2ZVCgEmbY8D1wu6UfgoJYst7zqRUbkf0DDt6+Jj5bK4vfTT+oP6rP8ml/5Vv4otrIf+CcPuj0jhMIhFVom5yGbmOXhNwdZ8=}
